
[unstable]
json-target-spec = true
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
[build]
target = "emkk.json"

[target.emkk]
rustflags = [
    "-C", "link-arg=./out/memory_impl.o",
    "-C", "link-arg=./out/x86_64.o",
    "-C", "link-arg=./out/interrupts_impl.o",
    "-C", "link-arg=./out/bootstrap.o",
    "-C", "link-arg=./out/time.o",
    "-C", "link-arg=./out/context_switch.o",
    "-C", "link-arg=-Tlinker.ld"
]
